"""Regression contracts for the real-event teaching visual probe."""
from __future__ import annotations

import copy
import json
import random
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [
    str(ROOT),
    str(ROOT / "sim"),
    str(ROOT / "tools/acceptance"),
    str(ROOT / "tools/mockups"),
]

from PIL import ImageFont
from tactical_visual_probe import label_font

import teaching_visual_probe as probe
from teaching_skill_prototype import PIECES, TEMPO, PrototypeBattle


RULESET = "tactics_v5"
STAT_MODE = "budget_v1"
AUDIT_DIR = ROOT / ".build/teaching-prototype/audit"
PACKET_CASES_PATH = AUDIT_DIR / "packet-cases.json"


def animation_for(battle):
    import render_battle_gif as renderer

    return renderer.BattleAnimation(
        [], [], 7, renderer.Front(), renderer.Palettes(), renderer.Font16(),
        battle=battle,
    )


def teaching_payload(event):
    return event[5]


def export_packet_case(name, battle, binding, reconciliation):
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    cases = {}
    if PACKET_CASES_PATH.exists():
        cases = json.loads(PACKET_CASES_PATH.read_text(encoding="utf-8"))
    cases[name] = {
        "source": "real PrototypeBattle generated by tests/test_teaching_visual_probe.py",
        "event_count": len(battle.events),
        "event_sha256": probe.digest(battle.events),
        "events": [list(event) for event in battle.events],
        "cause": {
            "parent_raw_index": binding.parent_raw_index,
            "teaching_raw_index": binding.raw_index,
            "machine_id": binding.machine_id,
            "owned_raw_indices": binding.owned,
        },
        "reconciliation": reconciliation,
    }
    PACKET_CASES_PATH.write_text(
        json.dumps(cases, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )


class FullNaturalPositiveContracts(unittest.TestCase):
    def test_full_natural_scenes_require_their_first_batch_machine(self):
        self.assertEqual(probe.MACHINE_BY_SCENE["full_natural"], "guardian_riposte")
        self.assertEqual(probe.MACHINE_BY_SCENE["tempo_full_natural"], "tempo_break")

    def test_removed_full_natural_teaching_cannot_become_a_negative_scene(self):
        _module, factory = probe.load_prototype()
        design, machines = probe.load_design_contract()

        def without_teaching(kind, scenario="valid", seed=7):
            battle = probe.unwrap_battle(factory(kind, scenario=scenario, seed=seed))
            battle.events = [event for event in battle.events
                             if event[1] != "teaching_effect"]
            return battle

        fonts = tuple(ImageFont.truetype(label_font(), size)
                      for size in (24, 18, 14))
        with tempfile.TemporaryDirectory() as directory:
            args = SimpleNamespace(out=Path(directory), font=None, fps=2)
            scenes = (("full_natural", "counter", "full"),)
            with patch.object(probe, "SCENES", scenes):
                with self.assertRaisesRegex(
                        AssertionError, "expected directed teaching event"):
                    probe.run_probe(
                        args, fonts, without_teaching, design, machines,
                        {"schema": "test-failure", "seed": 7},
                    )


    def test_full_natural_cases_export_real_cause_and_reconciliation(self):
        _module, factory = probe.load_prototype()
        _design, machines = probe.load_design_contract()
        for scene, kind, machine in (
            ("full_natural", "counter", "guardian_riposte"),
            ("tempo_full_natural", "tempo", "tempo_break"),
        ):
            with self.subTest(scene=scene):
                battle = probe.unwrap_battle(factory(kind, scenario="full", seed=7))
                animation = animation_for(battle)
                bindings = probe.collect_teachings(scene, battle, animation, machine)
                self.assertEqual(len(bindings), 1)
                probe.adapt_teaching_schedule(animation, bindings[0])
                reconciliation = probe.reconcile_parent_state(
                    scene, bindings[0], battle, animation,
                    machines[machine]["candidate_parameters"],
                )
                self.assertTrue(
                    reconciliation["semantic"]["hp_unchanged_by_teaching"])
                export_packet_case(scene, battle, bindings[0], reconciliation)

    def test_negative_scenes_reject_a_real_successful_teaching_packet(self):
        _module, factory = probe.load_prototype()
        design, machines = probe.load_design_contract()

        def unexpected_success(kind, scenario="valid", seed=7):
            return factory(kind, scenario="valid", seed=seed)

        fonts = tuple(ImageFont.truetype(label_font(), size)
                      for size in (24, 18, 14))
        for scene, kind, scenario in probe.SCENES:
            if scene in probe.POSITIVE_SCENES:
                continue
            with self.subTest(scene=scene), tempfile.TemporaryDirectory() as directory:
                args = SimpleNamespace(out=Path(directory), font=None, fps=2)
                with patch.object(probe, "SCENES", ((scene, kind, scenario),)):
                    with self.assertRaisesRegex(
                            AssertionError, "negative scenario emitted teaching_effect"):
                        probe.run_probe(args, fonts, unexpected_success, design, machines,
                                        {"schema": "test-failure", "seed": 7})


class NativePacketContracts(unittest.TestCase):
    def native_packet_battle(self):
        """A real tempo cast with one unwrapped splash hit and one native heal."""
        battle = PrototypeBattle(
            [PIECES[6]],
            [PIECES[143], PIECES[143], PIECES[143]],
            random.Random(7),
            experimental_a=[TEMPO],
            positions_a=[(2, 2)],
            positions_b=[(2, 1), (3, 1), (3, 0)],
            team_options=[None, {"partner": 143}],
            ruleset=RULESET,
            stat_mode=STAT_MODE,
            weather_name=None,
        )
        caster, target, side, patient = battle.units
        for unit in battle.units:
            unit.hp = unit.max_hp = 10_000
            unit.next_act = 0.1
        caster.energy = 100
        target.energy = side.energy = patient.energy = 0
        target.hp = patient.hp = 1_000
        caster.target_idx = target.idx
        battle.duration = 0.1
        battle.events = [(0.0, "deploy", unit.idx, unit.pos)
                         for unit in battle.units]
        for unit in battle.units:
            battle._emit_state(unit, 0.0)
        battle._act(caster, 0.1)
        return battle, caster, target, side, patient

    def binding(self, battle=None):
        battle = battle or self.native_packet_battle()[0]
        animation = animation_for(battle)
        bindings = probe.collect_teachings(
            "native_unwrapped_side_and_heal", battle, animation, TEMPO)
        self.assertEqual(len(bindings), 1)
        return battle, animation, bindings[0]

    def test_real_unwrapped_side_hit_and_native_heal_reconcile(self):
        battle, animation, binding = self.binding()
        marker = battle.events[binding.raw_index]
        parent = battle.events[binding.parent_raw_index]
        between = battle.events[binding.parent_raw_index + 1:binding.raw_index]
        heals = [event for event in between if event[1] == "partner_effect"]
        side_hits = [event for event in between
                     if event[1] == "attack" and event[3] != parent[3]]

        self.assertEqual((parent[1], parent[2], parent[3]), ("cast", 0, 1))
        self.assertEqual((marker[2], marker[3], marker[4]), (0, 1, TEMPO))
        self.assertEqual(len(heals), 1)
        self.assertEqual((heals[0][5], heals[0][2]), ("share_lunch", parent[3]))
        self.assertEqual(len(side_hits), 1)
        self.assertEqual((side_hits[0][2], side_hits[0][3]), (parent[2], 2))
        self.assertGreater(side_hits[0][4], 0)
        self.assertEqual(binding.owned, list(range(
            binding.raw_index + 1,
            binding.raw_index + 1 + teaching_payload(marker)["cause_event_count"],
        )))

        probe.adapt_teaching_schedule(animation, binding)
        _design, machines = probe.load_design_contract()
        reconciliation = probe.reconcile_parent_state(
            "native_unwrapped_side_and_heal", binding, battle, animation,
            machines[TEMPO]["candidate_parameters"],
        )
        self.assertEqual(reconciliation["semantic"]["actual_loss"], 10)
        self.assertTrue(reconciliation["semantic"]["hp_unchanged_by_teaching"])
        side_reconciliation = reconciliation["native_reconciliation"]["side_hits"][0]
        self.assertEqual(side_reconciliation["damage"],
                         side_reconciliation["hp_loss"])
        self.assertGreater(side_reconciliation["hp_loss"], 0)
        heal_reconciliation = reconciliation["native_reconciliation"]["heals"][0]
        self.assertEqual(heal_reconciliation["amount"],
                         heal_reconciliation["hp_gain"])
        self.assertGreater(heal_reconciliation["hp_gain"], 0)
        export_packet_case(
            "native_unwrapped_side_and_heal", battle, binding, reconciliation,
        )

    def test_broken_parent_cause_and_unrelated_native_events_are_rejected(self):
        battle, animation, binding = self.binding()

        broken = copy.deepcopy(battle)
        teaching_index = next(index for index, event in enumerate(broken.events)
                              if event[1] == "teaching_effect")
        marker = broken.events[teaching_index]
        side_index = next(index for index, event in enumerate(broken.events)
                          if event[1] == "attack" and event[3] == 2)
        marker = (*marker[:5], {**teaching_payload(marker), "cause_index": side_index})
        broken.events[teaching_index] = marker
        with self.assertRaisesRegex(
                AssertionError, "tempo_break source/target must match"):
            probe.collect_teachings(
                "tampered_parent", broken, animation, TEMPO)

        unrelated = copy.deepcopy(battle)
        cause = teaching_payload(
            next(event for event in unrelated.events if event[1] == "teaching_effect")
        )["cause_index"]
        unrelated.events.insert(cause + 1, (0.1, "move", 99, (5, 5)))
        with self.assertRaisesRegex(
                AssertionError, "unrelated unit"):
            probe.collect_teachings(
                "unrelated_event", unrelated, animation, TEMPO)

        for label, third_idx in (("side_target_move", 2), ("heal_patient_move", 3)):
            real_third_move = copy.deepcopy(battle)
            real_third_move.events.insert(
                cause + 1, (0.1, "move", third_idx, (5, 5)))
            with self.subTest(label=label):
                with self.assertRaisesRegex(
                        AssertionError, "unrelated unit"):
                    probe.collect_teachings(
                        label, real_third_move, animation, TEMPO)

        broken_owned = copy.deepcopy(battle)
        owned_index = teaching_payload(
            next(event for event in broken_owned.events
                 if event[1] == "teaching_effect")
        )["cause_event_count"]
        teaching_index = next(index for index, event in enumerate(broken_owned.events)
                              if event[1] == "teaching_effect")
        broken_owned.events[teaching_index + owned_index] = (
            0.1, "partner_effect", binding.parent[2], binding.parent[3], 143, "share_lunch",
            {"amount": 1},
        )
        with self.assertRaisesRegex(
                AssertionError, "unsupported kind"):
            probe.collect_teachings(
                "tampered_owned", broken_owned, animation, TEMPO)

        broken_heal = copy.deepcopy(battle)
        heal_index = next(index for index, event in enumerate(broken_heal.events)
                          if event[1] == "partner_effect")
        old = broken_heal.events[heal_index]
        broken_heal.events[heal_index] = (0.1, old[1], 0, old[3], *old[4:])
        with self.assertRaisesRegex(
                AssertionError, "native healing"):
            probe.collect_teachings(
                "tampered_heal", broken_heal, animation_for(broken_heal), TEMPO)



if __name__ == "__main__":
    unittest.main()
