"""Verified original choreography references; rendering adapts these scripts.

Names identify visual references, not new battle mechanics. Graphics are redrawn.
Stealth Rock and Stone Edge are later-generation concepts; rock_spikes uses the
verified Gen III Rock Tomb / Rock Slide / Spikes scripts as its pixel-art basis.
"""

REFERENCES = {'spark_chain': {'moves': [{'name': '十万伏特',
                            'symbol': 'Move_THUNDERBOLT',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1075'}],
                 'adaptation': '短促错拍电击与窄电弧；额外电链只连接真实连锁目标',
                 'basis': 'G3 原版动画脚本编排'},
 'four_arm_combo': {'moves': [{'name': '连续拳',
                               'symbol': 'Move_COMET_PUNCH',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1007'},
                              {'name': '音速拳',
                               'symbol': 'Move_MACH_PUNCH',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3125'},
                              {'name': '十字劈',
                               'symbol': 'Move_CROSS_CHOP',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6468'}],
                    'adaptation': '四个拳部发射点错拍冲击，命中处短促交叉拳痕',
                    'basis': 'G3 原版动画脚本编排'},
 'venom_rush': {'moves': [{'name': '毒针',
                           'symbol': 'Move_POISON_STING',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L816'},
                          {'name': '角撞',
                           'symbol': 'Move_HORN_ATTACK',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2423'},
                          {'name': '角钻（尖角钻）',
                           'symbol': 'Move_HORN_DRILL',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2465'}],
                'adaptation': '圆润锥体沿轴旋转前刺，弧形冲击面张开，毒屑曲向散开',
                'basis': 'G3 原版动画脚本编排'},
 'shadow_siphon': {'moves': [{'name': '影子球',
                              'symbol': 'Move_SHADOW_BALL',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7356'},
                             {'name': '终极吸取',
                              'symbol': 'Move_GIGA_DRAIN',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5814'}],
                   'adaptation': '有暗面与亮肩的影子球加速抵达，碎裂为卷烟；汲取回流只跟随真实效果',
                   'basis': 'G3 原版动画脚本编排'},
 'flame_storm': {'moves': [{'name': '大字爆炎',
                            'symbol': 'Move_FIRE_BLAST',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L856'}],
                 'adaptation': '保留已确认的火束、大字火焰与飞溅火星',
                 'basis': 'G3 原版动画脚本编排'},
 'psychic_blink': {'moves': [{'name': '瞬间移动',
                              'symbol': 'Move_TELEPORT',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2769'},
                             {'name': '精神强念',
                              'symbol': 'Move_PSYCHIC',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4733'}],
                   'adaptation': '施法者纵向拉伸，落点两侧念力弯面挤压，尾端收缩断裂',
                   'basis': 'G3 原版动画脚本编排'},
 'venom_armor': {'moves': [{'name': '溶化',
                            'symbol': 'Move_ACID_ARMOR',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2997'},
                           {'name': '毒针',
                            'symbol': 'Move_POISON_STING',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L816'}],
                 'adaptation': '溶化式局部防御准备与毒针硬脊绕身展开，实际近战反击才在来袭者处出现毒刺冲击',
                 'basis': 'G3 原版动画脚本编排'},
 'stone_pulse': {'moves': [{'name': '地震',
                            'symbol': 'Move_EARTHQUAKE',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2599'},
                           {'name': '岩石封锁',
                            'symbol': 'Move_ROCK_TOMB',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L9131'}],
                 'adaptation': '贴地震波、岩块突起与碎裂',
                 'basis': 'G3 原版动画脚本编排'},
 'flame_guard': {'moves': [{'name': '火焰轮',
                            'symbol': 'Move_FLAME_WHEEL',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L660'}],
                 'adaptation': '卷焰留在自身形成守护架势，实际嘲讽对象出现注意标记；不卷向敌人制造命中',
                 'basis': 'G3 原版动画脚本编排'},
 'venom_tide': {'moves': [{'name': '污泥炸弹',
                           'symbol': 'Move_SLUDGE_BOMB',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5962'},
                          {'name': '溶解液',
                           'symbol': 'Move_ACID',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6005'}],
                'adaptation': '错拍污泥抛射，命中形成厚湿面和黏滴，随后上浮毒泡',
                'basis': 'G3 原版动画脚本编排'},
 'twin_cannon': {'moves': [{'name': '水炮',
                            'symbol': 'Move_HYDRO_PUMP',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5612'}],
                 'adaptation': '两个炮口持续喷出独立实体水流，翻卷边缘与螺旋白沫，厚浪面弯曲散开',
                 'basis': 'G3 原版动画脚本编排'},
 'slow_field': {'moves': [{'name': '念力',
                           'symbol': 'Move_CONFUSION',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4716'}],
                'adaptation': '目标局部调色与形变，扁平慢透镜波面收缩散尽',
                'basis': 'G3 原版动画脚本编排'},
 'healing_song': {'moves': [{'name': '唱歌',
                             'symbol': 'Move_SING',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2550'},
                            {'name': '治愈铃声',
                             'symbol': 'Move_HEAL_BELL',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7708'}],
                  'adaptation': '流动音符指向真实友军，铃声恢复星屑仅随有效治疗事件展开',
                  'basis': 'G3 原版动画脚本编排'},
 'cleansing_powder': {'moves': [{'name': '催眠粉',
                                 'symbol': 'Move_SLEEP_POWDER',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L506'},
                                {'name': '麻痹粉',
                                 'symbol': 'Move_STUN_SPORE',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L482'},
                                {'name': '治愈铃声',
                                 'symbol': 'Move_HEAL_BELL',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7708'}],
                      'adaptation': '错层粉簇飘落，尾段逐渐散尽；净化星光只围绕真实接收者',
                      'basis': 'G3 原版动画脚本编排'},
 'moon_blessing': {'moves': [{'name': '月光',
                              'symbol': 'Move_MOONLIGHT',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3365'},
                             {'name': '祈愿',
                              'symbol': 'Move_WISH',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L8155'}],
                   'adaptation': '月光碎光抵达友军，实际护盾展开反射壁式透明光面；不附带治疗光点',
                   'basis': 'G3 原版动画脚本编排'},
 'aroma_garden': {'moves': [{'name': '芳香治疗',
                             'symbol': 'Move_AROMATHERAPY',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4137'},
                            {'name': '花瓣舞',
                             'symbol': 'Move_PETAL_DANCE',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6794'}],
                  'adaptation': '花瓣螺旋与轻盈香气，真实回复独立表现',
                  'basis': 'G3 原版动画脚本编排'},
 'solar_relay': {'moves': [{'name': '日光束（阳光烈焰）',
                            'symbol': 'Move_SOLAR_BEAM',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5437'},
                           {'name': '终极吸取',
                            'symbol': 'Move_GIGA_DRAIN',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5814'}],
                 'adaptation': '花心吸收光球后射出持续亮芯光束，命中迸出光屑',
                 'basis': 'G3 原版动画脚本编排'},
 'star_resonance': {'moves': [{'name': '泡沫光线',
                               'symbol': 'Move_BUBBLE_BEAM',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2190'},
                              {'name': '高速星星',
                               'symbol': 'Move_SWIFT',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L530'},
                              {'name': '自我再生',
                               'symbol': 'Move_RECOVER',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7569'}],
                    'adaptation': '自我再生的环绕星光与蓄电式光球组合，向真实友军递送能量；无水束攻击或治疗闪光',
                    'basis': 'G3 原版动画脚本编排'},
 'rock_spikes': {'moves': [{'name': '岩石封锁',
                            'symbol': 'Move_ROCK_TOMB',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L9131'},
                           {'name': '岩崩',
                            'symbol': 'Move_ROCK_SLIDE',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2119'},
                           {'name': '撒菱',
                            'symbol': 'Move_SPIKES',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6092'}],
                 'adaptation': '尖石抛向真实三格地形并贴地落下，铺设不伤人；进入岩钉才产生碎石冲击',
                 'basis': 'G3 原版动画脚本编排'},
 'sweeping_kick': {'moves': [{'name': '踢倒',
                              'symbol': 'Move_LOW_KICK',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2586'},
                             {'name': '回旋踢',
                              'symbol': 'Move_ROLLING_KICK',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2385'}],
                   'adaptation': '低位扫腿弧与瞬时足部冲击',
                   'basis': 'G3 原版动画脚本编排'},
 'rescue_tongue': {'moves': [{'name': '舌舔',
                              'symbol': 'Move_LICK',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7371'},
                             {'name': '自我再生',
                              'symbol': 'Move_RECOVER',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7569'}],
                   'adaptation': '软组织舌头伸向真实受伤友军，回收阶段衔接实际救援位移与恢复',
                   'basis': 'G3 原版动画脚本编排'},
 'root_domain': {'moves': [{'name': '扎根',
                            'symbol': 'Move_INGRAIN',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7836'},
                           {'name': '藤鞭',
                            'symbol': 'Move_VINE_WHIP',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1513'}],
                 'adaptation': '有粗细和明暗的藤根贴地生长，缠绕后回抽、散落叶屑',
                 'basis': 'G3 原版动画脚本编排'},
 'life_pulse': {'moves': [{'name': '炸蛋',
                           'symbol': 'Move_EGG_BOMB',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7331'},
                          {'name': '生蛋',
                           'symbol': 'Move_SOFT_BOILED',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7685'}],
                'adaptation': '蛋形回复载体递送给真实伤员，蛋壳散开与恢复光点只表达救护',
                'basis': 'G3 原版动画脚本编排'},
 'barrier_relay': {'moves': [{'name': '幻象光线',
                              'symbol': 'Move_PSYBEAM',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7134'},
                             {'name': '光墙',
                              'symbol': 'Move_LIGHT_SCREEN',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5026'},
                             {'name': '反射壁',
                              'symbol': 'Move_REFLECT',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5066'},
                             {'name': '屏障',
                              'symbol': 'Move_BARRIER',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5083'}],
                   'adaptation': '平行透明光面碎片递送到友军，真实护盾展开屏障；实际净化独立表现',
                   'basis': 'G3 原版动画脚本编排'},
 'storm_conductor': {'moves': [{'name': '打雷',
                                'symbol': 'Move_THUNDER',
                                'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4770'}],
                     'adaptation': '粗细分层的重雷柱从上方落下，短分叉与受压弧面强化接触',
                     'basis': 'G3 原版动画脚本编排'},
 'armor_pincer': {'moves': [{'name': '夹住',
                             'symbol': 'Move_VICE_GRIP',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1841'}],
                  'adaptation': '两个真实钳口发起相向切击，交汇处短促命中闪',
                  'basis': 'G3 原版动画脚本编排'},
 'gale_cross': {'moves': [{'name': '劈开',
                           'symbol': 'Move_SLASH',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3034'},
                          {'name': '旋风刀',
                           'symbol': 'Move_RAZOR_WIND',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7515'}],
                'adaptation': '斜向刀痕与旋转风刃，命中后尾流散开',
                'basis': 'G3 原版动画脚本编排'},
 'bull_rush': {'moves': [{'name': '猛撞',
                          'symbol': 'Move_TAKE_DOWN',
                          'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L760'}],
               'adaptation': '前冲速度线与近身撞击，落点碎尘',
               'basis': 'G3 原版动画脚本编排'},
 'frost_shelter': {'moves': [{'name': '冰冻之风',
                              'symbol': 'Move_ICY_WIND',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2228'},
                             {'name': '冰冻光束',
                              'symbol': 'Move_ICE_BEAM',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5351'},
                             {'name': '自我再生',
                              'symbol': 'Move_RECOVER',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7569'}],
                   'adaptation': '碎冰雾片递送到友军，光墙和神秘守护式环绕光层仅随实际护盾展开；不射出冰冻光束',
                   'basis': 'G3 原版动画脚本编排'},
 'cliff_swoop': {'moves': [{'name': '翅膀攻击',
                            'symbol': 'Move_WING_ATTACK',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6170'},
                           {'name': '岩崩',
                            'symbol': 'Move_ROCK_SLIDE',
                            'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2119'}],
                 'adaptation': '双翼短痕接落石碎裂',
                 'basis': 'G3 原版动画脚本编排'},
 'alert_tail': {'moves': [{'name': '摔打',
                           'symbol': 'Move_SLAM',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1489'},
                          {'name': '摇尾巴',
                           'symbol': 'Move_TAIL_WHIP',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1195'}],
                'adaptation': '圆厚尾部沿弯曲轨迹拍落，局部压缩后扫开尘屑',
                'basis': 'G3 原版动画脚本编排'},
 'toxic_spines': {'moves': [{'name': '飞弹针',
                             'symbol': 'Move_PIN_MISSILE',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L702'},
                            {'name': '撒菱',
                             'symbol': 'Move_SPIKES',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6092'}],
                  'adaptation': '三枚有硬脊暗底的毒针错拍弧线飞行，实际落点散开钉刺',
                  'basis': 'G3 原版动画脚本编排'},
 'mud_anchor': {'moves': [{'name': '掷泥',
                           'symbol': 'Move_MUD_SLAP',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5220'},
                          {'name': '浊流',
                           'symbol': 'Move_MUDDY_WATER',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L8601'}],
                'adaptation': '厚泥团低抛后铺成贴地泥浪，黏湿碎块落下并收散',
                'basis': 'G3 原版动画脚本编排'},
 'spinning_cleanup': {'moves': [{'name': '高速旋转',
                                 'symbol': 'Move_RAPID_SPIN',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3346'}],
                      'adaptation': '绕身旋转残影、横向尘线与近身撞击',
                      'basis': 'G3 原版动画脚本编排'},
 'watchful_lullaby': {'moves': [{'name': '起风',
                                 'symbol': 'Move_GUST',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6152'},
                                {'name': '唱歌',
                                 'symbol': 'Move_SING',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2550'},
                                {'name': '治愈铃声',
                                 'symbol': 'Move_HEAL_BELL',
                                 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7708'}],
                      'adaptation': '唱歌式旋转音符指向异常友军，真实净化与回能分别显示；无伤害风带',
                      'basis': 'G3 原版动画脚本编排'},
 'beacon_relay': {'moves': [{'name': '萤火',
                             'symbol': 'Move_TAIL_GLOW',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3896'},
                            {'name': '电磁波',
                             'symbol': 'Move_THUNDER_WAVE',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1124'}],
                  'adaptation': '萤火蓄光与蓄电光球组成弯曲能量流，实际友军接收能量；无回复或攻击电波',
                  'basis': 'G3 原版动画脚本编排'},
 'charged_beacon': {'moves': [{'name': '电磁炮',
                               'symbol': 'Move_ZAP_CANNON',
                               'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7203'}],
                    'adaptation': '深色电球压扁后撕成绕身电弧，与纵向落雷分开编排',
                    'basis': 'G3 原版动画脚本编排'},
 'fracture_vision': {'moves': [{'name': '预知未来',
                                'symbol': 'Move_FUTURE_SIGHT',
                                'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4750'}],
                     'adaptation': '两道错位预见波面形成剪切感，真实命中时局部压缩与闪光',
                     'basis': 'G3 原版动画脚本编排'},
 'horn_pressure': {'moves': [{'name': '超级角击',
                              'symbol': 'Move_MEGAHORN',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6109'},
                             {'name': '角钻（尖角钻）',
                              'symbol': 'Move_HORN_DRILL',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2465'}],
                   'adaptation': '有阴影体积的角钻与旋转螺纹，厚冲击面压入后舒展碎裂',
                   'basis': 'G3 原版动画脚本编排'},
 'moon_guard': {'moves': [{'name': '奇异之光',
                           'symbol': 'Move_CONFUSE_RAY',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2051'},
                          {'name': '反射壁',
                           'symbol': 'Move_REFLECT',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5066'},
                          {'name': '屏障',
                           'symbol': 'Move_BARRIER',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5083'}],
                'adaptation': '暗光球抵达后反弹散开，真实守护展开蓝色反射壁',
                'basis': 'G3 原版动画脚本编排'},
 'iron_fault': {'moves': [{'name': '铁尾',
                           'symbol': 'Move_IRON_TAIL',
                           'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7251'}],
                'adaptation': '有金属明暗面的宽尾击横扫，接触形成短压面与金属碎屑',
                'basis': 'G3 原版动画脚本编排'},
 'bliss_chorus': {'moves': [{'name': '治愈铃声',
                             'symbol': 'Move_HEAL_BELL',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7708'},
                            {'name': '喝牛奶',
                             'symbol': 'Move_MILK_DRINK',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3297'}],
                  'adaptation': '小铃波与跳动音符形成合唱节奏，真实回复伴随环绕光与上升星光',
                  'basis': 'G3 原版动画脚本编排'},
 'cinder_eruption': {'moves': [{'name': '喷火',
                                'symbol': 'Move_ERUPTION',
                                'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3805'}],
                     'adaptation': '一块主热岩带次级熔块抛起、错拍坠落，撞出炽热碎屑',
                     'basis': 'G3 原版动画脚本编排'},
 'cross_bullet': {'moves': [{'name': '金属爪',
                             'symbol': 'Move_METAL_CLAW',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7291'},
                            {'name': '音速拳',
                             'symbol': 'Move_MACH_PUNCH',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3125'}],
                  'adaptation': '双钳交叉金属切痕与短促拳压',
                  'basis': 'G3 原版动画脚本编排'},
 'dragon_crosscurrent': {'moves': [{'name': '水炮',
                                    'symbol': 'Move_HYDRO_PUMP',
                                    'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5612'},
                                   {'name': '龙息',
                                    'symbol': 'Move_DRAGON_BREATH',
                                    'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4931'}],
                         'adaptation': '粗细起伏的旋流水柱与弯曲浪面，龙属性追加只跟随真实侧击',
                         'basis': 'G3 原版动画脚本编排'},
 'undertow_lock': {'moves': [{'name': '潮旋',
                              'symbol': 'Move_WHIRLPOOL',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6365'},
                             {'name': '冲浪',
                              'symbol': 'Move_SURF',
                              'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6304'}],
                   'adaptation': '厚实旋转水体与翻卷浪唇，泡沫水滴离心甩出',
                   'basis': 'G3 原版动画脚本编排'},
 'crag_citadel': {'moves': [{'name': '岩崩',
                             'symbol': 'Move_ROCK_SLIDE',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2119'},
                            {'name': '沙暴',
                             'symbol': 'Move_SANDSTORM',
                             'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6345'}],
                  'adaptation': '错落岩块与贴地砂流，碎岩保护墙随真实事件显示',
                  'basis': 'G3 原版动画脚本编排'},
 'verdant_sanctuary': {'moves': [{'name': '花瓣舞',
                                  'symbol': 'Move_PETAL_DANCE',
                                  'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L6794'},
                                 {'name': '芳香治疗',
                                  'symbol': 'Move_AROMATHERAPY',
                                  'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L4137'},
                                 {'name': '光合作用',
                                  'symbol': 'Move_SYNTHESIS',
                                  'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5913'}],
                       'adaptation': '叶片与花瓣交错上旋，清露散落；恢复光环围绕真实患者',
                       'basis': 'G3 原版动画脚本编排'}}


# Current assistance identities retain legacy art only for historical enemy casts.
REFERENCES['star_resonance']['legacy_moves'] = REFERENCES['star_resonance']['moves']
REFERENCES['star_resonance']['moves'] = [
    {'name': '自我再生', 'symbol': 'Move_RECOVER', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7569'},
    {'name': '蓄电', 'symbol': 'Move_CHARGE', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3570'},
    {'name': '高速星星', 'symbol': 'Move_SWIFT', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L530'},
]
REFERENCES['barrier_relay']['legacy_moves'] = REFERENCES['barrier_relay']['moves']
REFERENCES['barrier_relay']['moves'] = [
    {'name': '光墙', 'symbol': 'Move_LIGHT_SCREEN', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5026'},
    {'name': '反射壁', 'symbol': 'Move_REFLECT', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5066'},
    {'name': '屏障', 'symbol': 'Move_BARRIER', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5083'},
]
REFERENCES['frost_shelter']['legacy_moves'] = REFERENCES['frost_shelter']['moves']
REFERENCES['frost_shelter']['moves'] = [
    {'name': '光墙', 'symbol': 'Move_LIGHT_SCREEN', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5026'},
    {'name': '神秘守护', 'symbol': 'Move_SAFEGUARD', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L1799'},
    {'name': '反射壁', 'symbol': 'Move_REFLECT', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L5066'},
]
REFERENCES['watchful_lullaby']['legacy_moves'] = REFERENCES['watchful_lullaby']['moves']
REFERENCES['watchful_lullaby']['moves'] = [
    {'name': '唱歌', 'symbol': 'Move_SING', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L2550'},
    {'name': '治愈铃声', 'symbol': 'Move_HEAL_BELL', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L7708'},
    {'name': '蓄电', 'symbol': 'Move_CHARGE', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3570'},
]
REFERENCES['beacon_relay']['legacy_moves'] = REFERENCES['beacon_relay']['moves']
REFERENCES['beacon_relay']['moves'] = [
    {'name': '萤火', 'symbol': 'Move_TAIL_GLOW', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3896'},
    {'name': '蓄电', 'symbol': 'Move_CHARGE', 'url': 'https://github.com/pret/pokeemerald/blob/731ad5bfd6e6f265508d0efcca0ba42f9dcf5881/data/battle_anim_scripts.s#L3570'},
]
